version: '3.1'

services:
  savoie:
    restart: always
    build: ./
    container_name: savoie_dev
    env_file: .env
    environment:
      - NODE_ENV=development
    entrypoint: 
      - yarn
      - dev:docker
    volumes:
      - ./apps:/app/apps
      - ./src:/app/src   
      - ./package.json:/app/package.json
      - ./.env:/app/.env
    networks:
      - caddy

networks:
  caddy:
    external:
      name: caddy-node_caddy