version: '3.1'

services:
  savoie:
    restart: always
    image: node:alpine
    container_name: savoie_edge
    env_file: .env
    working_dir: /app
    entrypoint: 
      - yarn
      - dev   
    volumes:
      - ./:/app
    ports:
      - 3600:3600