version: '3.1'

services:
  savoie_dev:
    restart: always
    build: ./
    container_name: savoie_dev
    ports:
      - 7374:3000
    env_file: .env
    entrypoint: 
      - yarn
      - dev:docker
    volumes:
      - ./apps:/app/apps
      - ./src:/app/src   
    networks:
      - default

networks:
  default:
    external:
      name: wraddy_backend