version: '3.1'

services:
  savoie:
    restart: always
    build: ./
    container_name: savoie
    ports:
      - 7373:3000
    env_file: .env
    entrypoint: 
      - yarn
      - start:docker   
    volumes:
      - ./.env:/app/.env  
      - ./src:/app/src
      - ./apps:/app/apps
    networks:
      - default

networks:
  default:
    external:
      name: wraddy_backend