version: '3.1'

services:
  savoie:
    restart: always
    build: ./
    container_name: savoie
    env_file: .env
    environment:
      - NODE_ENV=production
    entrypoint: 
      - yarn
      - start   
    networks:
      - caddy

networks:
  caddy:
    external:
      name: caddy-node_caddy