version: '3.1'

services:
  savoie:
    restart: always
    build: ./
    container_name: savoie
    ports:
      - 7373:3000
    env_file: .env
    environment:
      - NODE_ENV=production
    entrypoint: 
      - yarn
      - start   
    networks:
      - default

networks:
  default:
    external:
      name: wraddy_backend